### ISSUE TITLE
Error while running react-native run-android

### ISSUE THREAD

**Issue by kpachhai** [cyber-republic/react-native-elastos-wallet-core-demo#10]
I get the following error: 

```json
Project with path ':libs' could not be found in project ':react-native-elastos-wallet-core'.
Open File```

**Comment by kpachhai** [comment]
looks like ```jsoninclude ':libs'``` needs to be appended to settings.gradle file

**Comment by mukulverm4** [comment]
This is still an issue. Even after appending `include :'libs'` I am getting the following error:

` Unable to find a matching configuration of project :libs: None of the consumable configurations have attributes.`

**Comment by EricDualc** [comment]
This is because it doesn't load the latest elastos-wallet-core code as npm module.
@ademcan When I do `npm install`, it doesn't load the latest one. Actually, on wallet core, I added ElastosWallet library, the libs library was from old version.
Would you please update it?

**Comment by ademcan** [comment]
I have added the C -> Cpp switch to the npm package repository and as the demo still uses the C library, that might be the issue. In such case using 1.0.4 should work then. Could you please try:
npm uninstall react-native-elastos-wallet-core
npm install  react-native-elastos-wallet-core@1.0.4

**Comment by EricDualc** [comment]
oh, I guess you are mentioning about ios part.
I meant android part. libs library what @mukulverm4 said was from old version. Right now, the library was changed by ElastosWallet.

**Comment by ademcan** [comment]
Ok I got it now. The issue is that the npm package is based on my own fork of the repo (until we create an official CR account on npmjs and publish our packages under that name). The recent switch to the cpp library for iOS made the package too big and npmjs does not accept it. I therefore cannot update the npm package at the moment with the recent Android related changes. However, we can use the following commands to install the correct version:

npm uninstall react-native-elastos-wallet-core
npm install cyber-republic/react-native-elastos-wallet-core

This will install the most recent version of the react-native-elastos-wallet-core package which includes your commits related to Android.

**Comment by EricDualc** [comment]
Great, thanks @ademcan 
@mukulverm4 Please follow the above instructions.
